# ruff config that must pass. Use it with CI as follows:
# `ruff check --config ruff_essential.toml .`

[lint]
select = [
  "E9",
  "F63",
  "F7",
  "F82",
  "FA102",  # Python 3.10-style union typing is used so we need to import `from __future__ import annotations`
]
