# Check ruff format and isort applied correctly

name: Style checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.10"
      - name: Run ruff
        run: |
          ruff_requirement=$(awk '/^ruff==/ {print $1; exit}' requirements-ci.txt)
          set +e  # Do not exit shell on ruff failure
          out=$(uvx --from "$ruff_requirement" ruff format --check --diff . 2> app_stderr.txt)

          exit_code=$?
          err=$(<app_stderr.txt)

          # Display the raw output in the step
          echo "${out}"
          echo "${err}"

          # Display the Markdown output in the job summary
          { echo "\`\`\`diff"; echo "${out}"; echo "${err}"; echo "\`\`\`"; } >> "$GITHUB_STEP_SUMMARY"

          # Exit with the exit-code returned by ruff
          exit ${exit_code}

  ruff-isort:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.10"
      - name: Run ruff
        run: |
          ruff_requirement=$(awk '/^ruff==/ {print $1; exit}' requirements-ci.txt)
          set +e  # Do not exit shell on ruff failure
          out=$(uvx --from "$ruff_requirement" ruff check --select I --diff . 2> app_stderr.txt)

          exit_code=$?
          err=$(<app_stderr.txt)

          # Display the raw output in the step
          echo "${out}"
          echo "${err}"

          # Display the Markdown output in the job summary
          { echo "\`\`\`diff"; echo "${out}"; echo "${err}"; echo "\`\`\`"; } >> "$GITHUB_STEP_SUMMARY"

          # Exit with the exit-code returned by ruff
          exit ${exit_code}
